#Docker file for payment app

FROM node:20-alpine AS build
WORKDIR /app/   
COPY ./src/payment/package*.json ./
RUN apk add --no-cache python3 make g++ && npm ci --omit=dev

##----------------
FROM node:20-alpine 
USER node
WORKDIR /app/

COPY NODE_ENV=production
COPY --chown=node:node --from=build /app/node_modules/ ./node_modules/
COPY ./src/payment/ ./
COPY ./pb/demo.proto ./

EXPOSE 50051
ENTRYPOINT ["npm","run","start"]
